import type {NextPage} from 'next';
import Head from 'next/head';
import {H} from '../shared/ui/atoms/h/H';
import {GlobalStyle} from '../shared/styles/globalStyles';
import {Span} from '../shared/ui/atoms/span/Span';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <GlobalStyle/>
      <H kind="h1">Head</H>
      <Span kind="xxs">Span</Span>
    </div>
  );
};

export default Home;
